name: Artifact Demo
on:
  workflow_dispatch:

jobs:
  upload-artifact:
    on: ubuntu-latest
    env: 
      project-name: demonstration of artifact
      version: 1
    steps:
      - name: project information
        run: echo $project-name version : $version
      - name: create file
        run: echo "Hello Artifact" >> message.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with: 
         name: my-file
         path: message.txt
